[package]
name = "speedrun-kata"
version = "0.1.0"
authors = ["Buissart-Dubois, Julien <github@steranoid.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
